
// Guide/Controls
i18n.en.guideControls = '<li><kbd>F11</kbd> / double click - Toggle fullscreen</li><li><kbd>M</kbd> - Settings</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - User Manual</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - next channel</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - previous channel</li><li><kbd>&#8678;</kbd> - open channel list</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - open group list and other options</li><li><kbd>&#8680;</kbd> - close channel/group list</li><li><kbd>&#9003;</kbd> - play last channel</li><li><kbd>ESC</kbd> - close current operating mask</li>';
i18n.es.guideControls = '<li><kbd>F11</kbd> / doble clic - Alternar pantalla completa</li><li><kbd>M</kbd> - ConfiguraciÃ³n</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manual del usuario</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - siguiente canal</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - canal anterior</li><li><kbd>&#8678;</kbd> - abrir lista de canales</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - abrir lista de grupos y otras opciones</li><li><kbd>&#8680;</kbd> - cerrar lista de canales/grupos</li><li><kbd>&#9003;</kbd> - reproducir Ãºltimo canal</li><li><kbd>ESC</kbd> - cerrar la mÃ¡scara de operaciÃ³n actual</li>';
i18n.it.guideControls = '<li><kbd>F11</kbd> / doppio click - Attiva/disattiva schermo intero</li><li><kbd>M</kbd> - Impostazioni</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manuale utente</li><li><kbd>&#8679;</kbd> / scorrimento del mouse SU - canale successivo</li><li><kbd>&#8681;</kbd> / scorrimento del mouse GIÃ™ - canale precedente</li><li><kbd>&#8678;</kbd> - apri l\'elenco dei canali</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - apri elenco gruppi e altre opzioni</li><li><kbd>&#8680;</kbd> - chiudi elenco canali/gruppi</li><li><kbd>&#9003;</kbd> - riproduci l\'ultimo canale</li><li><kbd>ESC</kbd> - chiude la maschera operativa corrente</li>';
i18n.fr.guideControls = '<li><kbd>F11</kbd> / double clic - Basculer en plein Ã©cran</li><li><kbd>M</kbd> - ParamÃ¨tres</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manuel de l\'utilisateur</li><li><kbd>&#8679;</kbd> / mouse-scroll UP - chaÃ®ne suivante</li><li><kbd>&#8681;</kbd> / mouse-scroll DOWN - chaÃ®ne prÃ©cÃ©dente</li><li><kbd>&#8678;</kbd> - ouvrir la liste des chaÃ®nes</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - ouvrir la liste des groupes et autres options</li><li><kbd>&#8680;</kbd> - fermer la liste des canaux/groupes</li><li><kbd>&#9003;</kbd> - lire la derniÃ¨re chaÃ®ne</li><li><kbd>ESC</kbd> - fermer le masque de fonctionnement actuel</li>';
i18n.de.guideControls = '<li><kbd>F11</kbd> / Doppelklick - Vollbild umschalten</li><li><kbd>M</kbd> - Einstellungen</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Benutzerhandbuch</li><li><kbd>&#8679;</kbd> / Maus nach oben scrollen - nÃ¤chster Kanal</li><li><kbd>&#8681;</kbd> / Maus nach unten scrollen - vorheriger Kanal</li><li><kbd>&#8678;</kbd> - Kanalliste Ã¶ffnen</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Gruppenliste und andere Optionen Ã¶ffnen</li><li><kbd>&#8680;</kbd> - Kanal-/Gruppenliste schlieÃŸen</li><li><kbd>&#9003;</kbd> - Letzten Kanal abspielen</li><li><kbd>ESC</kbd> - Aktuelle Bedienmaske schlieÃŸen</li>';
i18n.ru.guideControls = '<li><kbd>F11</kbd> / Ğ”Ğ²Ğ¾Ğ¹Ğ½Ğ¾Ğ¹ ĞºĞ»Ğ¸Ğº - Ğ’ĞºĞ»ÑÑ‡Ğ¸Ñ‚ÑŒ Ğ¿Ğ¾Ğ»Ğ½Ğ¾ÑĞºÑ€Ğ°Ğ½Ğ½Ñ‹Ğ¹ Ñ€ĞµĞ¶Ğ¸Ğ¼</li><li><kbd>M</kbd> - ĞĞ°ÑÑ‚Ñ€Ğ¾Ğ¹ĞºĞ¸</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Ğ ÑƒĞºĞ¾Ğ²Ğ¾Ğ´ÑÑ‚Ğ²Ğ¾ Ğ¿Ğ¾Ğ»ÑŒĞ·Ğ¾Ğ²Ğ°Ñ‚ĞµĞ»Ñ< /li><li><kbd>&#8679;</kbd> / Ğ¿Ñ€Ğ¾ĞºÑ€ÑƒÑ‚ĞºĞ° Ğ¼Ñ‹ÑˆĞ¸ Ğ’Ğ’Ğ•Ğ Ğ¥ â€” ÑĞ»ĞµĞ´ÑƒÑÑ‰Ğ¸Ğ¹ ĞºĞ°Ğ½Ğ°Ğ»</li><li><kbd>&#8681;</kbd> / Ğ¿Ñ€Ğ¾ĞºÑ€ÑƒÑ‚ĞºĞ° Ğ¼Ñ‹ÑˆĞ¸ Ğ’ĞĞ˜Ğ— â€” Ğ¿Ñ€ĞµĞ´Ñ‹Ğ´ÑƒÑ‰Ğ¸Ğ¹ ĞºĞ°Ğ½Ğ°Ğ»</li><li><kbd>&#8678;</kbd> - Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚ÑŒ ÑĞ¿Ğ¸ÑĞ¾Ğº ĞºĞ°Ğ½Ğ°Ğ»Ğ¾Ğ²</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚ÑŒ ÑĞ¿Ğ¸ÑĞ¾Ğº Ğ³Ñ€ÑƒĞ¿Ğ¿ Ğ¸ Ğ´Ñ€ÑƒĞ³Ğ¸Ğµ Ğ¿Ğ°Ñ€Ğ°Ğ¼ĞµÑ‚Ñ€Ñ‹</li><li><kbd>&#8680;</kbd> - Ğ·Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ ÑĞ¿Ğ¸ÑĞ¾Ğº ĞºĞ°Ğ½Ğ°Ğ»Ğ¾Ğ²/Ğ³Ñ€ÑƒĞ¿Ğ¿</li><li><kbd>&#9003;</kbd> - Ğ²Ğ¾ÑĞ¿Ñ€Ğ¾Ğ¸Ğ·Ğ²ĞµÑÑ‚Ğ¸ Ğ¿Ğ¾ÑĞ»ĞµĞ´Ğ½Ğ¸Ğ¹ ĞºĞ°Ğ½Ğ°Ğ»</li><li><kbd>ESC</kbd> - Ğ·Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ Ñ‚ĞµĞºÑƒÑ‰ÑƒÑ Ñ€Ğ°Ğ±Ğ¾Ñ‡ÑƒÑ Ğ¼Ğ°ÑĞºÑƒ</li>';
i18n.tr.guideControls = '<li><kbd>F11</kbd> / Ã§ift tÄ±klama - Tam ekran geÃ§iÅŸ</li><li><kbd>M</kbd> - Ayarlar</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - KullanÄ±m KÄ±lavuzu</li><li><kbd>&#8679;</kbd> / mouse-scroll YUKARI - sonraki kanal</li><li><kbd>&#8681;</kbd> / mouse-scroll AÅAÄI - Ã¶nceki kanal</li><li><kbd>&#8678;</kbd> - kanal listesini aÃ§</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - grup listesini ve diÄŸer seÃ§enekleri aÃ§</li><li><kbd>&#8680;</kbd> - kanal/grup listesini kapat</li><li><kbd>&#9003;</kbd> - son kanalÄ± oynat</li><li><kbd>ESC</kbd> - geÃ§erli iÅŸlem maskesini kapat</li>';
i18n.pl.guideControls = '<li><kbd>F11</kbd> / podwÃ³jne klikniÄ™cie - PrzeÅ‚Ä…cz peÅ‚ny ekran</li><li><kbd>M</kbd> - Ustawienia</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Instrukcja obsÅ‚ugi</li><li><kbd>&#8679;</kbd> / scroll myszÄ… W GÃ“RÄ˜ - nastÄ™pny kanaÅ‚</li><li><kbd>&#8681;</kbd> / scroll myszÄ… W DÃ“Å - poprzedni kanaÅ‚</li><li><kbd>&#8678;</kbd> - otwÃ³rz listÄ™ kanaÅ‚Ã³w</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - otwÃ³rz listÄ™ grup i inne opcje</li><li><kbd>&#8680;</kbd> - zamknij listÄ™ kanaÅ‚Ã³w/grup</li><li><kbd>&#9003;</kbd> - odtwÃ³rz ostatni kanaÅ‚</li><li><kbd>ESC</kbd> - zamknij bieÅ¼Ä…cÄ… maskÄ™ operacyjnÄ…</li>';
i18n.pt.guideControls = '<li><kbd>F11</kbd> / clique duplo - Alternar tela cheia</li><li><kbd>M</kbd> - ConfiguraÃ§Ãµes</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manual do UsuÃ¡rio</li><li><kbd>&#8679;</kbd> / rolar do mouse PARA CIMA - prÃ³ximo canal</li><li><kbd>&#8681;</kbd> / rolar do mouse PARA BAIXO - canal anterior</li><li><kbd>&#8678;</kbd> - abrir lista de canais</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - abrir lista de grupos e outras opÃ§Ãµes</li><li><kbd>&#8680;</kbd> - fechar lista de canais/grupos</li><li><kbd>&#9003;</kbd> - reproduzir Ãºltimo canal</li><li><kbd>ESC</kbd> - fechar mÃ¡scara operacional atual</li>';
i18n.cs.guideControls = '<li><kbd>F11</kbd> / dvojklik - PÅ™epnout na celou obrazovku</li><li><kbd>M</kbd> - NastavenÃ­</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - UÅ¾ivatelskÃ¡ pÅ™Ã­ruÄka</li><li><kbd>&#8679;</kbd> / rolovÃ¡nÃ­ myÅ¡Ã­ nahoru - dalÅ¡Ã­ kanÃ¡l</li><li><kbd>&#8681;</kbd> / rolovÃ¡nÃ­ myÅ¡Ã­ dolÅ¯ - pÅ™edchozÃ­ kanÃ¡l</li><li><kbd>&#8678;</kbd> - otevÅ™Ã­t seznam kanÃ¡lÅ¯</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - otevÅ™Ã­t seznam skupin a dalÅ¡Ã­ moÅ¾nosti</li><li><kbd>&#8680;</kbd> - zavÅ™Ã­t seznam kanÃ¡lÅ¯/skupin</li><li><kbd>&#9003;</kbd> - pÅ™ehrÃ¡t poslednÃ­ kanÃ¡l</li><li><kbd>ESC</kbd> - zavÅ™Ã­t aktuÃ¡lnÃ­ operaÄnÃ­ masku</li>';
i18n.ar.guideControls = '<li><kbd>F11</kbd> / Ø§Ù„Ù†Ù‚Ø± Ø§Ù„Ù…Ø²Ø¯ÙˆØ¬ - ØªØ¨Ø¯ÙŠÙ„ ÙˆØ¶Ø¹ Ù…Ù„Ø¡ Ø§Ù„Ø´Ø§Ø´Ø©</li><li><kbd>M</kbd> - Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Ø¯Ù„ÙŠÙ„ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…</li><li><kbd>&#8679;</kbd> / ØªÙ…Ø±ÙŠØ± Ø§Ù„Ù…Ø§ÙˆØ³ Ù„Ø£Ø¹Ù„Ù‰ - Ø§Ù„Ù‚Ù†Ø§Ø© Ø§Ù„ØªØ§Ù„ÙŠØ©</li><li><kbd>&#8681;</kbd> / ØªÙ…Ø±ÙŠØ± Ø§Ù„Ù…Ø§ÙˆØ³ Ù„Ø£Ø³ÙÙ„ - Ø§Ù„Ù‚Ù†Ø§Ø© Ø§Ù„Ø³Ø§Ø¨Ù‚Ø©</li><li><kbd>&#8678;</kbd> - ÙØªØ­ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ù‚Ù†ÙˆØ§Øª</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - ÙØªØ­ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª ÙˆØ®ÙŠØ§Ø±Ø§Øª Ø£Ø®Ø±Ù‰</li><li><kbd>&#8680;</kbd> - Ø¥ØºÙ„Ø§Ù‚ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ù‚Ù†ÙˆØ§Øª/Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª</li><li><kbd>&#9003;</kbd> - ØªØ´ØºÙŠÙ„ Ø¢Ø®Ø± Ù‚Ù†Ø§Ø©</li><li><kbd>ESC</kbd> - Ø¥ØºÙ„Ø§Ù‚ Ø§Ù„Ù‚Ù†Ø§Ø¹ Ø§Ù„ØªØ´ØºÙŠÙ„ÙŠ Ø§Ù„Ø­Ø§Ù„ÙŠ</li>';
i18n.fi.guideControls = '<li><kbd>F11</kbd> / kaksoisnapsautus - Vaihda koko nÃ¤yttÃ¶</li><li><kbd>M</kbd> - Asetukset</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - KÃ¤yttÃ¶opas</li><li><kbd>&#8679;</kbd> / hiiren vieritys YLÃ–S - seuraava kanava</li><li><kbd>&#8681;</kbd> / hiiren vieritys ALAS - edellinen kanava</li><li><kbd>&#8678;</kbd> - avaa kanavalista</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - avaa ryhmÃ¤lista ja muut asetukset</li><li><kbd>&#8680;</kbd> - sulje kanava/ryhmÃ¤lista</li><li><kbd>&#9003;</kbd> - toista viimeisin kanava</li><li><kbd>ESC</kbd> - sulje nykyinen toimintanaamari</li>';
i18n.ro.guideControls = '<li><kbd>F11</kbd> / dublu clic - Comutare ecran complet</li><li><kbd>M</kbd> - SetÄƒri</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Manualul utilizatorului</li><li><kbd>&#8679;</kbd> / derulare mouse SUS - canalul urmÄƒtor</li><li><kbd>&#8681;</kbd> / derulare mouse JOS - canalul anterior</li><li><kbd>&#8678;</kbd> - deschide lista de canale</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - deschide lista de grupuri È™i alte opÈ›iuni</li><li><kbd>&#8680;</kbd> - Ã®nchide lista de canale/grupuri</li><li><kbd>&#9003;</kbd> - redÄƒ ultimul canal</li><li><kbd>ESC</kbd> - Ã®nchide masca de operare curentÄƒ</li>';
i18n.no.guideControls = '<li><kbd>F11</kbd> / dobbeltklikk - Bytt til fullskjerm</li><li><kbd>M</kbd> - Innstillinger</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - BrukerhÃ¥ndbok</li><li><kbd>&#8679;</kbd> / musehjul OPP - neste kanal</li><li><kbd>&#8681;</kbd> / musehjul NED - forrige kanal</li><li><kbd>&#8678;</kbd> - Ã¥pne kanallisten</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Ã¥pne gruppelisten og andre alternativer</li><li><kbd>&#8680;</kbd> - lukk kanal-/gruppeliste</li><li><kbd>&#9003;</kbd> - spill siste kanal</li><li><kbd>ESC</kbd> - lukk gjeldende operasjonsmaske</li>';
i18n.el.guideControls = '<li><kbd>F11</kbd> / Î´Î¹Ï€Î»ÏŒ ÎºÎ»Î¹Îº - Î•Î½Î±Î»Î»Î±Î³Î® Ï€Î»Î®ÏÎ·Ï‚ Î¿Î¸ÏŒÎ½Î·Ï‚</li><li><kbd>M</kbd> - Î¡Ï…Î¸Î¼Î¯ÏƒÎµÎ¹Ï‚</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Î•Î³Ï‡ÎµÎ¹ÏÎ¯Î´Î¹Î¿ Ï‡ÏÎ®ÏƒÏ„Î·</li><li><kbd>&#8679;</kbd> / ÎºÏÎ»Î¹ÏƒÎ· Ï€Î¿Î½Ï„Î¹ÎºÎ¹Î¿Ï Î Î¡ÎŸÎ£ Î¤Î‘ Î Î‘ÎÎ© - ÎµÏ€ÏŒÎ¼ÎµÎ½Î¿ ÎºÎ±Î½Î¬Î»Î¹</li><li><kbd>&#8681;</kbd> / ÎºÏÎ»Î¹ÏƒÎ· Ï€Î¿Î½Ï„Î¹ÎºÎ¹Î¿Ï Î Î¡ÎŸÎ£ Î¤Î‘ ÎšÎ‘Î¤Î© - Ï€ÏÎ¿Î·Î³Î¿ÏÎ¼ÎµÎ½Î¿ ÎºÎ±Î½Î¬Î»Î¹</li><li><kbd>&#8678;</kbd> - Î±Î½Î¿Î¯Î¾Ï„Îµ Ï„Î· Î»Î¯ÏƒÏ„Î± ÎºÎ±Î½Î±Î»Î¹ÏÎ½</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Î±Î½Î¿Î¯Î¾Ï„Îµ Ï„Î· Î»Î¯ÏƒÏ„Î± Î¿Î¼Î¬Î´Ï‰Î½ ÎºÎ±Î¹ Î¬Î»Î»ÎµÏ‚ ÎµÏ€Î¹Î»Î¿Î³Î­Ï‚</li><li><kbd>&#8680;</kbd> - ÎºÎ»ÎµÎ¯ÏƒÏ„Îµ Ï„Î· Î»Î¯ÏƒÏ„Î± ÎºÎ±Î½Î±Î»Î¹ÏÎ½/Î¿Î¼Î¬Î´Ï‰Î½</li><li><kbd>&#9003;</kbd> - Ï€Î±Î¯Î¾Ï„Îµ Ï„Î¿ Ï„ÎµÎ»ÎµÏ…Ï„Î±Î¯Î¿ ÎºÎ±Î½Î¬Î»Î¹</li><li><kbd>ESC</kbd> - ÎºÎ»ÎµÎ¯ÏƒÏ„Îµ Ï„Î·Î½ Ï„ÏÎ­Ï‡Î¿Ï…ÏƒÎ± Î¼Î¬ÏƒÎºÎ± Î»ÎµÎ¹Ï„Î¿Ï…ÏÎ³Î¯Î±Ï‚</li>';
i18n.ko.guideControls = '<li><kbd>F11</kbd> / ë”ë¸” í´ë¦­ - ì „ì²´ í™”ë©´ ì „í™˜</li><li><kbd>M</kbd> - ì„¤ì •</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - ì‚¬ìš©ì ë§¤ë‰´ì–¼</li><li><kbd>&#8679;</kbd> / ë§ˆìš°ìŠ¤ ìŠ¤í¬ë¡¤ UP - ë‹¤ìŒ ì±„ë„</li><li><kbd>&#8681;</kbd> / ë§ˆìš°ìŠ¤ ìŠ¤í¬ë¡¤ DOWN - ì´ì „ ì±„ë„</li><li><kbd>&#8678;</kbd> - ì±„ë„ ëª©ë¡ ì—´ê¸°</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - ê·¸ë£¹ ëª©ë¡ ë° ê¸°íƒ€ ì˜µì…˜ ì—´ê¸°</li><li><kbd>&#8680;</kbd> - ì±„ë„/ê·¸ë£¹ ëª©ë¡ ë‹«ê¸°</li><li><kbd>&#9003;</kbd> - ë§ˆì§€ë§‰ ì±„ë„ ì¬ìƒ</li><li><kbd>ESC</kbd> - í˜„ì¬ ì‘ì—… ë§ˆìŠ¤í¬ ë‹«ê¸°</li>';
i18n.vi.guideControls = '<li><kbd>F11</kbd> / Double click - Chuyá»ƒn Ä‘á»•i toÃ n mÃ n hÃ¬nh</li><li><kbd>M</kbd> - CÃ i Ä‘áº·t</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - HÆ°á»›ng dáº«n sá»­ dá»¥ng</li><li><kbd>&#8679;</kbd> / LÄƒn chuá»™t LÃŠN - KÃªnh káº¿ tiáº¿p</li><li><kbd>&#8681;</kbd> / LÄƒn chuá»™t XUá»NG - KÃªnh trÆ°á»›c Ä‘Ã³</li><li><kbd>&#8678;</kbd> - Má»Ÿ danh sÃ¡ch kÃªnh</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Má»Ÿ danh sÃ¡ch nhÃ³m vÃ  cÃ¡c tÃ¹y chá»n khÃ¡c</li><li><kbd>&#8680;</kbd> - ÄÃ³ng danh sÃ¡ch kÃªnh/nhÃ³m</li><li><kbd>&#9003;</kbd> - PhÃ¡t láº¡i kÃªnh cuá»‘i cÃ¹ng</li><li><kbd>ESC</kbd> - ÄÃ³ng máº·t náº¡ hoáº¡t Ä‘á»™ng hiá»‡n táº¡i</li>';
i18n.uk.guideControls = '<li><kbd>F11</kbd> / Ğ¿Ğ¾Ğ´Ğ²Ñ–Ğ¹Ğ½Ğ¸Ğ¹ ĞºĞ»Ñ–Ğº - ĞŸĞµÑ€ĞµĞºĞ»ÑÑ‡Ğ¸Ñ‚Ğ¸ Ğ½Ğ° Ğ¿Ğ¾Ğ²Ğ½Ğ¸Ğ¹ ĞµĞºÑ€Ğ°Ğ½</li><li><kbd>M</kbd> - ĞĞ°Ğ»Ğ°ÑˆÑ‚ÑƒĞ²Ğ°Ğ½Ğ½Ñ</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - ĞšĞµÑ€Ñ–Ğ²Ğ½Ğ¸Ñ†Ñ‚Ğ²Ğ¾ ĞºĞ¾Ñ€Ğ¸ÑÑ‚ÑƒĞ²Ğ°Ñ‡Ğ°</li><li><kbd>&#8679;</kbd> / Ğ¿Ñ€Ğ¾ĞºÑ€ÑƒÑ‚ĞºĞ° Ğ¼Ğ¸ÑˆĞµÑ Ğ’Ğ“ĞĞ Ğ£ - Ğ½Ğ°ÑÑ‚ÑƒĞ¿Ğ½Ğ¸Ğ¹ ĞºĞ°Ğ½Ğ°Ğ»</li><li><kbd>&#8681;</kbd> / Ğ¿Ñ€Ğ¾ĞºÑ€ÑƒÑ‚ĞºĞ° Ğ¼Ğ¸ÑˆĞµÑ Ğ”ĞĞ›Ğ£ - Ğ¿Ğ¾Ğ¿ĞµÑ€ĞµĞ´Ğ½Ñ–Ğ¹ ĞºĞ°Ğ½Ğ°Ğ»</li><li><kbd>&#8678;</kbd> - Ğ²Ñ–Ğ´ĞºÑ€Ğ¸Ñ‚Ğ¸ ÑĞ¿Ğ¸ÑĞ¾Ğº ĞºĞ°Ğ½Ğ°Ğ»Ñ–Ğ²</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - Ğ²Ñ–Ğ´ĞºÑ€Ğ¸Ñ‚Ğ¸ ÑĞ¿Ğ¸ÑĞ¾Ğº Ğ³Ñ€ÑƒĞ¿ Ñ‚Ğ° Ñ–Ğ½ÑˆÑ– Ğ¾Ğ¿Ñ†Ñ–Ñ—</li><li><kbd>&#8680;</kbd> - Ğ·Ğ°ĞºÑ€Ğ¸Ñ‚Ğ¸ ÑĞ¿Ğ¸ÑĞ¾Ğº ĞºĞ°Ğ½Ğ°Ğ»Ñ–Ğ²/Ğ³Ñ€ÑƒĞ¿</li><li><kbd>&#9003;</kbd> - Ğ²Ñ–Ğ´Ñ‚Ğ²Ğ¾Ñ€Ğ¸Ñ‚Ğ¸ Ğ¾ÑÑ‚Ğ°Ğ½Ğ½Ñ–Ğ¹ ĞºĞ°Ğ½Ğ°Ğ»</li><li><kbd>ESC</kbd> - Ğ·Ğ°ĞºÑ€Ğ¸Ñ‚Ğ¸ Ğ¿Ğ¾Ñ‚Ğ¾Ñ‡Ğ½Ğµ Ğ²Ñ–ĞºĞ½Ğ¾</li>';
i18n.id.guideControls = '<li><kbd>F11</kbd> / double click - Aktifkan mode layar penuh</li><li><kbd>M</kbd> - Pengaturan</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - Panduan Pengguna</li><li><kbd>&#8679;</kbd> / mouse-scroll ATAS - channel berikutnya</li><li><kbd>&#8681;</kbd> / mouse-scroll BAWAH - channel sebelumnya</li><li><kbd>&#8678;</kbd> - buka daftar channel</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - buka daftar grup dan opsi lainnya</li><li><kbd>&#8680;</kbd> - tutup daftar channel/grup</li><li><kbd>&#9003;</kbd> - mainkan channel terakhir</li><li><kbd>ESC</kbd> - tutup masker operasi saat ini</li>';
i18n.ja.guideControls = '<li><kbd>F11</kbd> / ãƒ€ãƒ–ãƒ«ã‚¯ãƒªãƒƒã‚¯ - ãƒ•ãƒ«ã‚¹ã‚¯ãƒªãƒ¼ãƒ³åˆ‡ã‚Šæ›¿ãˆ</li><li><kbd>M</kbd> - è¨­å®š</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒãƒ‹ãƒ¥ã‚¢ãƒ«</li><li><kbd>&#8679;</kbd> / ãƒã‚¦ã‚¹ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ« UP - æ¬¡ã®ãƒãƒ£ãƒ³ãƒãƒ«</li><li><kbd>&#8681;</kbd> / ãƒã‚¦ã‚¹ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ« DOWN - å‰ã®ãƒãƒ£ãƒ³ãƒãƒ«</li><li><kbd>&#8678;</kbd> - ãƒãƒ£ãƒ³ãƒãƒ«ãƒªã‚¹ãƒˆã‚’é–‹ã</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - ã‚°ãƒ«ãƒ¼ãƒ—ãƒªã‚¹ãƒˆãŠã‚ˆã³ä»–ã®ã‚ªãƒ—ã‚·ãƒ§ãƒ³ã‚’é–‹ã</li><li><kbd>&#8680;</kbd> - ãƒãƒ£ãƒ³ãƒãƒ«/ã‚°ãƒ«ãƒ¼ãƒ—ãƒªã‚¹ãƒˆã‚’é–‰ã˜ã‚‹</li><li><kbd>&#9003;</kbd> - æœ€å¾Œã®ãƒãƒ£ãƒ³ãƒãƒ«ã‚’å†ç”Ÿ</li><li><kbd>ESC</kbd> - ç¾åœ¨ã®æ“ä½œç”»é¢ã‚’é–‰ã˜ã‚‹</li>';
i18n.hi.guideControls = '<li><kbd>F11</kbd> / à¤¡à¤¬à¤² à¤•à¥à¤²à¤¿à¤• - à¤«à¥à¤² à¤¸à¥à¤•à¥à¤°à¥€à¤¨ à¤šà¤¾à¤²à¥‚/à¤¬à¤‚à¤¦</li><li><kbd>M</kbd> - à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸</li><li><kbd>E</kbd> - EPG</li><li><kbd>H</kbd> - à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾ à¤®à¤¾à¤°à¥à¤—à¤¦à¤°à¥à¤¶à¤¿à¤•à¤¾</li><li><kbd>&#8679;</kbd> / à¤®à¤¾à¤‰à¤¸ à¤¸à¥à¤•à¥à¤°à¥‰à¤² UP - à¤…à¤—à¤²à¤¾ à¤šà¥ˆà¤¨à¤²</li><li><kbd>&#8681;</kbd> / à¤®à¤¾à¤‰à¤¸ à¤¸à¥à¤•à¥à¤°à¥‰à¤² DOWN - à¤ªà¤¿à¤›à¤²à¤¾ à¤šà¥ˆà¤¨à¤²</li><li><kbd>&#8678;</kbd> - à¤šà¥ˆà¤¨à¤² à¤¸à¥‚à¤šà¥€ à¤–à¥‹à¤²à¥‡à¤‚</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - à¤¸à¤®à¥‚à¤¹ à¤¸à¥‚à¤šà¥€ à¤”à¤° à¤…à¤¨à¥à¤¯ à¤µà¤¿à¤•à¤²à¥à¤ª à¤–à¥‹à¤²à¥‡à¤‚</li><li><kbd>&#8680;</kbd> - à¤šà¥ˆà¤¨à¤²/à¤¸à¤®à¥‚à¤¹ à¤¸à¥‚à¤šà¥€ à¤¬à¤‚à¤¦ à¤•à¤°à¥‡à¤‚</li><li><kbd>&#9003;</kbd> - à¤…à¤‚à¤¤à¤¿à¤® à¤šà¥ˆà¤¨à¤² à¤šà¤²à¤¾à¤à¤‚</li><li><kbd>ESC</kbd> - à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨ à¤‘à¤ªà¤°à¥‡à¤¶à¤¨ à¤¸à¥à¤•à¥à¤°à¥€à¤¨ à¤¬à¤‚à¤¦ à¤•à¤°à¥‡à¤‚</li>';
i18n.zh.guideControls = '<li><kbd>F11</kbd> / åŒå‡» - åˆ‡æ¢å…¨å±</li><li><kbd>M</kbd> - è®¾ç½®</li><li><kbd>E</kbd> - ç”µå­èŠ‚ç›®æŒ‡å—ï¼ˆEPGï¼‰</li><li><kbd>H</kbd> - ç”¨æˆ·æ‰‹å†Œ</li><li><kbd>&#8679;</kbd> / é¼ æ ‡å‘ä¸Šæ»šåŠ¨ - ä¸‹ä¸€ä¸ªé¢‘é“</li><li><kbd>&#8681;</kbd> / é¼ æ ‡å‘ä¸‹æ»šåŠ¨ - ä¸Šä¸€ä¸ªé¢‘é“</li><li><kbd>&#8678;</kbd> - æ‰“å¼€é¢‘é“åˆ—è¡¨</li><li><kbd>&#8678;</kbd><kbd>&#8678;</kbd> - æ‰“å¼€åˆ†ç»„åˆ—è¡¨å’Œå…¶ä»–é€‰é¡¹</li><li><kbd>&#8680;</kbd> - å…³é—­é¢‘é“/åˆ†ç»„åˆ—è¡¨</li><li><kbd>&#9003;</kbd> - æ’­æ”¾ä¸Šä¸€ä¸ªé¢‘é“</li><li><kbd>ESC</kbd> - å…³é—­å½“å‰æ“ä½œç•Œé¢</li>';


// CORS
i18n.en.corsHint = 'âš  Some channels might not play due to strict CORS policy. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">More info and how to fix this</a>.';
i18n.es.corsHint = 'âš  Es posible que algunos canales no se reproduzcan debido a la estricta polÃ­tica de CORS. <a href="https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">MÃ¡s informaciÃ³n y cÃ³mo solucionarlo.</a>';
i18n.it.corsHint = 'âš  Alcuni canali potrebbero non essere riprodotti a causa della rigida politica CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Ulteriori informazioni e come risolvere il problema.</a>';
i18n.fr.corsHint = 'âš  Certaines chaÃ®nes peuvent ne pas jouer en raison de la politique stricte de CORS. <a href="https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Plus d\'informations et comment rÃ©soudre ce problÃ¨me.</a>';
i18n.de.corsHint = 'âš  Einige KanÃ¤le kÃ¶nnen aufgrund strenger CORS-Richtlinien mÃ¶glicherweise nicht abgespielt werden. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Weitere Informationen und wie du dies beheben kannst.</a>';
i18n.ru.corsHint = 'âš  ĞĞµĞºĞ¾Ñ‚Ğ¾Ñ€Ñ‹Ğµ ĞºĞ°Ğ½Ğ°Ğ»Ñ‹ Ğ¼Ğ¾Ğ³ÑƒÑ‚ Ğ½Ğµ Ğ²Ğ¾ÑĞ¿Ñ€Ğ¾Ğ¸Ğ·Ğ²Ğ¾Ğ´Ğ¸Ñ‚ÑŒÑÑ Ğ¸Ğ·-Ğ·Ğ° ÑÑ‚Ñ€Ğ¾Ğ³Ğ¾Ğ¹ Ğ¿Ğ¾Ğ»Ğ¸Ñ‚Ğ¸ĞºĞ¸ CORS. <a href="https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">ĞŸĞ¾Ğ´Ñ€Ğ¾Ğ±Ğ½ĞµĞµ Ğ¾ Ñ‚Ğ¾Ğ¼, ĞºĞ°Ğº ÑÑ‚Ğ¾ Ğ¸ÑĞ¿Ñ€Ğ°Ğ²Ğ¸Ñ‚ÑŒ.</Ğ°>';
i18n.tr.corsHint = 'âš  KatÄ± CORS politikasÄ± nedeniyle bazÄ± kanallar oynatÄ±lamayabilir. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Daha fazla bilgi ve bunun nasÄ±l dÃ¼zeltileceÄŸi</a>.';
i18n.pl.corsHint = 'âš  NiektÃ³re kanaÅ‚y mogÄ… nie byÄ‡ odtwarzane ze wzglÄ™du na surowe zasady CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">WiÄ™cej informacji i jak to naprawiÄ‡</a>.';
i18n.pt.corsHint = 'âš  Alguns canais podem nÃ£o ser reproduzidos devido Ã  polÃ­tica rÃ­gida do CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Mais informaÃ§Ãµes e como corrigir isso</a>.';
i18n.cs.corsHint = 'âš  NÄ›kterÃ© kanÃ¡ly se nemusÃ­ pÅ™ehrÃ¡vat kvÅ¯li pÅ™Ã­snÃ½m zÃ¡sadÃ¡m CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">DalÅ¡Ã­ informace a jak to opravit</a>.';
i18n.ar.corsHint = 'âš  Ù‚Ø¯ Ù„Ø§ ØªØ¹Ù…Ù„ Ø¨Ø¹Ø¶ Ø§Ù„Ù‚Ù†ÙˆØ§Øª Ø¨Ø³Ø¨Ø¨ Ø³ÙŠØ§Ø³Ø© CORS Ø§Ù„ØµØ§Ø±Ù…Ø©. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Ù…Ø²ÙŠØ¯ Ù…Ù† Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª ÙˆÙƒÙŠÙÙŠØ© Ø¥ØµÙ„Ø§Ø­ Ù‡Ø°Ø§</a>.';
i18n.fi.corsHint = 'âš  Jotkut kanavat eivÃ¤t vÃ¤lttÃ¤mÃ¤ttÃ¤ toistu tiukan CORS-kÃ¤ytÃ¤nnÃ¶n vuoksi. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">LisÃ¤tietoja ja kuinka korjata tÃ¤mÃ¤</a>.';
i18n.ro.corsHint = 'âš  Este posibil ca unele canale sÄƒ nu fie redate din cauza politicii stricte CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Mai multe informaÈ›ii È™i cum sÄƒ remediaÈ›i acest lucru</a>.';
i18n.no.corsHint = 'âš  Noen kanaler kan ikke spille pÃ¥ grunn av strenge CORS-policyer. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Mer informasjon og hvordan du fikser dette</a>.';
i18n.el.corsHint = 'âš  ÎŸÏÎ¹ÏƒÎ¼Î­Î½Î± ÎºÎ±Î½Î¬Î»Î¹Î± ÎµÎ½Î´Î­Ï‡ÎµÏ„Î±Î¹ Î½Î± Î¼Î·Î½ Ï€Î±Î¯Î¶Î¿Ï…Î½ Î»ÏŒÎ³Ï‰ Î±Ï…ÏƒÏ„Î·ÏÎ®Ï‚ Ï€Î¿Î»Î¹Ï„Î¹ÎºÎ®Ï‚ CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Î ÎµÏÎ¹ÏƒÏƒÏŒÏ„ÎµÏÎµÏ‚ Ï€Î»Î·ÏÎ¿Ï†Î¿ÏÎ¯ÎµÏ‚ ÎºÎ±Î¹ Ï€ÏÏ‚ Î½Î± Ï„Î¿ Î´Î¹Î¿ÏÎ¸ÏÏƒÎµÏ„Îµ</a>.';
i18n.ko.corsHint = 'âš  ì¼ë¶€ ì±„ë„ì€ ì—„ê²©í•œ CORS ì •ì±… ë•Œë¬¸ì— ì¬ìƒë˜ì§€ ì•Šì„ ìˆ˜ ìˆìŠµë‹ˆë‹¤. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">ìì„¸í•œ ì •ë³´ ë° í•´ê²° ë°©ë²•</a>.';
i18n.vi.corsHint = 'âš  Má»™t sá»‘ kÃªnh cÃ³ thá»ƒ khÃ´ng phÃ¡t Ä‘Æ°á»£c do chÃ­nh sÃ¡ch CORS nghiÃªm ngáº·t. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">ThÃ´ng tin chi tiáº¿t vÃ  cÃ¡ch kháº¯c phá»¥c</a>.';
i18n.uk.corsHint = 'âš  Ğ”ĞµÑĞºÑ– ĞºĞ°Ğ½Ğ°Ğ»Ğ¸ Ğ¼Ğ¾Ğ¶ÑƒÑ‚ÑŒ Ğ½Ğµ Ğ¿Ñ€Ğ°Ñ†ÑĞ²Ğ°Ñ‚Ğ¸ Ñ‡ĞµÑ€ĞµĞ· ÑÑ‚Ñ€Ğ¾Ğ³Ñƒ Ğ¿Ğ¾Ğ»Ñ–Ñ‚Ğ¸ĞºÑƒ CORS. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Ğ‘Ñ–Ğ»ÑŒÑˆĞµ Ñ–Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ñ–Ñ— Ñ‚Ğ° ÑĞº Ğ²Ğ¸Ğ¿Ñ€Ğ°Ğ²Ğ¸Ñ‚Ğ¸ Ñ†Ğµ</a>.';
i18n.id.corsHint = 'âš  Beberapa saluran mungkin tidak dapat diputar karena kebijakan CORS yang ketat. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">Informasi lebih lanjut dan cara mengatasi masalah ini</a>.';
i18n.ja.corsHint = 'âš  ä¸€éƒ¨ã®ãƒãƒ£ãƒ³ãƒãƒ«ã¯å³æ ¼ãªCORSãƒãƒªã‚·ãƒ¼ã«ã‚ˆã‚Šå†ç”Ÿã•ã‚Œãªã„å¯èƒ½æ€§ãŒã‚ã‚Šã¾ã™ã€‚ <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">è©³ç´°æƒ…å ±ã¨è§£æ±ºæ–¹æ³•</a>ã€‚';
i18n.hi.corsHint = 'âš  à¤•à¥à¤› à¤šà¥ˆà¤¨à¤² à¤¸à¤–à¥à¤¤ CORS à¤¨à¥€à¤¤à¤¿ à¤•à¥‡ à¤•à¤¾à¤°à¤£ à¤¨à¤¹à¥€à¤‚ à¤šà¤² à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤ <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">à¤…à¤§à¤¿à¤• à¤œà¤¾à¤¨à¤•à¤¾à¤°à¥€ à¤”à¤° à¤‡à¤¸à¥‡ à¤ à¥€à¤• à¤•à¤°à¤¨à¥‡ à¤•à¤¾ à¤¤à¤°à¥€à¤•à¤¾</a>à¥¤';
i18n.zh.corsHint = 'âš  ç”±äºä¸¥æ ¼çš„CORSæ”¿ç­–ï¼Œä¸€äº›é¢‘é“å¯èƒ½æ— æ³•æ’­æ”¾ã€‚ <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin" target="_blank">æ›´å¤šä¿¡æ¯åŠè§£å†³æ–¹æ³•</a>ã€‚';


// First hint in settings
i18n.en.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Insert demo playlist</span><br><br><span class="LINK" onclick="showGuide();">show user guide</span>';
i18n.es.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Insertar lista de reproducciÃ³n de demostraciÃ³n</span><br><br><span class="LINK" onclick="showGuide();">mostrar la guÃ­a del usuario</span>';
i18n.it.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Inserisci playlist demo</span><br><br><span class="LINK" onclick="showGuide();">mostra la guida per l\'utente</span>';
i18n.fr.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">InsÃ©rer une playlist de dÃ©monstration</span><br><br><span class="LINK" onclick="showGuide();">afficher le guide de l\'utilisateur</span>';
i18n.de.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Demo Kanalliste einfÃ¼gen</span><br><br><span class="LINK" onclick="showGuide();">Bedienungsanleitung anzeigen</span>';
i18n.ru.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Ğ’ÑÑ‚Ğ°Ğ²Ğ¸Ñ‚ÑŒ Ğ´ĞµĞ¼Ğ¾Ğ½ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ğ¾Ğ½Ğ½Ñ‹Ğ¹ Ğ¿Ğ»ĞµĞ¹Ğ»Ğ¸ÑÑ‚</span><br><br><span class="LINK" onclick="showGuide();">Ğ¿Ğ¾ĞºĞ°Ğ·Ğ°Ñ‚ÑŒ Ñ€ÑƒĞºĞ¾Ğ²Ğ¾Ğ´ÑÑ‚Ğ²Ğ¾ Ğ¿Ğ¾Ğ»ÑŒĞ·Ğ¾Ğ²Ğ°Ñ‚ĞµĞ»Ñ</span>';
i18n.tr.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Demo Ã§alma listesi ekle</span><br><br><span class="LINK" onclick="showGuide();">kullanÄ±m kÄ±lavuzunu gÃ¶ster</span>';
i18n.pl.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Wstaw playlistÄ™ demonstracyjnÄ…</span><br><br><span class="LINK" onclick="showGuide();">pokaÅ¼ instrukcjÄ™ obsÅ‚ugi</span>';
i18n.pt.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Inserir playlist demo</span><br><br><span class="LINK" onclick="showGuide();">mostrar guia do usuÃ¡rio</span>';
i18n.cs.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">VloÅ¾te demo playlist</span><br><br><span class="LINK" onclick="showGuide();">zobrazit uÅ¾ivatelskou pÅ™Ã­ruÄku</span>';
i18n.ar.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Ø£Ø¯Ø®Ù„ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„ØªØ´ØºÙŠÙ„ Ø§Ù„ØªØ¬Ø±ÙŠØ¨ÙŠØ©</span><br><br><span class="LINK" onclick="showGuide();">Ø¹Ø±Ø¶ Ø¯Ù„ÙŠÙ„ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…</span>';
i18n.fi.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">LisÃ¤Ã¤ demosoittolista</span><br><br><span class="LINK" onclick="showGuide();">nÃ¤ytÃ¤ kÃ¤yttÃ¶ohje</span>';
i18n.ro.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">InseraÈ›i lista de redare demonstrativÄƒ</span><br><br><span class="LINK" onclick="showGuide();">arata ghidul utilizatorului</span>';
i18n.no.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Sett inn demospilleliste</span><br><br><span class="LINK" onclick="showGuide();">vis brukerveiledning</span>';
i18n.el.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Î•Î¹ÏƒÎ±Î³Ï‰Î³Î® Î»Î¯ÏƒÏ„Î±Ï‚ Î±Î½Î±Ï€Î±ÏÎ±Î³Ï‰Î³Î®Ï‚ ÎµÏ€Î¯Î´ÎµÎ¹Î¾Î·Ï‚</span><br><br><span class="LINK" onclick="showGuide();">ÎµÎ¼Ï†Î¬Î½Î¹ÏƒÎ· Î¿Î´Î·Î³Î¿Ï Ï‡ÏÎ®ÏƒÏ„Î·</span>';
i18n.ko.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">ë°ëª¨ í”Œë ˆì´ë¦¬ìŠ¤íŠ¸ ì‚½ì…</span><br><br><span class="LINK" onclick="showGuide();">ì‚¬ìš©ì ê°€ì´ë“œ í‘œì‹œ</span>';
i18n.vi.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">ChÃ¨n danh sÃ¡ch phÃ¡t máº«u</span><br><br><span class="LINK" onclick="showGuide();">hiá»ƒn thá»‹ hÆ°á»›ng dáº«n sá»­ dá»¥ng</span>';
i18n.uk.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Ğ’ÑÑ‚Ğ°Ğ²Ğ¸Ñ‚Ğ¸ Ğ´ĞµĞ¼Ğ¾-Ğ¿Ğ»ĞµĞ¹Ğ»Ğ¸ÑÑ‚</span><br><br><span class="LINK" onclick="showGuide();">Ğ¿Ğ¾ĞºĞ°Ğ·Ğ°Ñ‚Ğ¸ Ğ¿Ğ¾ÑÑ–Ğ±Ğ½Ğ¸Ğº ĞºĞ¾Ñ€Ğ¸ÑÑ‚ÑƒĞ²Ğ°Ñ‡Ğ°</span>';
i18n.id.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">Masukkan daftar putar demo</span><br><br><span class="LINK" onclick="showGuide();">tampilkan panduan pengguna</span>';
i18n.ja.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">ãƒ‡ãƒ¢ãƒ—ãƒ¬ã‚¤ãƒªã‚¹ãƒˆã‚’æŒ¿å…¥</span><br><br><span class="LINK" onclick="showGuide();">ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚¬ã‚¤ãƒ‰ã‚’è¡¨ç¤º</span>';
i18n.hi.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">à¤¡à¥‡à¤®à¥‹ à¤ªà¥à¤²à¥‡à¤²à¤¿à¤¸à¥à¤Ÿ à¤¡à¤¾à¤²à¥‡à¤‚</span><br><br><span class="LINK" onclick="showGuide();">à¤¯à¥‚à¤œà¤° à¤—à¤¾à¤‡à¤¡ à¤¦à¤¿à¤–à¤¾à¤à¤‚</span>';
i18n.zh.helpHint = '<span class="LINK" onclick="insertDemoPlaylistUrl();">æ’å…¥æ¼”ç¤ºæ’­æ”¾åˆ—è¡¨</span><br><br><span class="LINK" onclick="showGuide();">æ˜¾ç¤ºç”¨æˆ·æŒ‡å—</span>';


var sDonateLink = '<br><a href="https://m3u-ip.tv/?donate=1" target="_blank">https://m3u-ip.tv</a>';
// Donate without QR-codes for browser/mobile
i18n.en.donate = 'If you like, you can leave a donation:' + sDonateLink;
i18n.es.donate = 'Si gustas, puedes dejar una donaciÃ³n:' + sDonateLink;
i18n.it.donate = 'Se vuoi, puoi lasciare una donazione:' + sDonateLink;
i18n.fr.donate = 'Si vous le souhaitez, vous pouvez faire un don:' + sDonateLink;
i18n.de.donate = 'Wenn du mÃ¶chtest, kannst du etwas spenden:' + sDonateLink;
i18n.ru.donate = 'Ğ•ÑĞ»Ğ¸ Ñ…Ğ¾Ñ‚Ğ¸Ñ‚Ğµ, Ğ¼Ğ¾Ğ¶ĞµÑ‚Ğµ Ğ¾ÑÑ‚Ğ°Ğ²Ğ¸Ñ‚ÑŒ Ğ¿Ğ¾Ğ¶ĞµÑ€Ñ‚Ğ²Ğ¾Ğ²Ğ°Ğ½Ğ¸Ğµ:' + sDonateLink;
i18n.tr.donate = 'Dilerseniz baÄŸÄ±ÅŸ bÄ±rakabilirsiniz:' + sDonateLink;
i18n.pl.donate = 'JeÅ›li chcesz, moÅ¼esz zostawiÄ‡ darowiznÄ™:' + sDonateLink;
i18n.pt.donate = 'Se quiser, pode deixar uma doaÃ§Ã£o:' + sDonateLink;
i18n.cs.donate = 'Pokud chcete, mÅ¯Å¾ete zanechat dar:' + sDonateLink;
i18n.ar.donate = 'Ø¥Ø°Ø§ Ø£Ø±Ø¯Øª ØŒ ÙŠÙ…ÙƒÙ†Ùƒ ØªØ±Ùƒ ØªØ¨Ø±Ø¹: ' + sDonateLink;
i18n.fi.donate = 'Halutessasi voit jÃ¤ttÃ¤Ã¤ lahjoituksen:' + sDonateLink;
i18n.ro.donate = 'DacÄƒ doriÈ›i, puteÈ›i lÄƒsa o donaÈ›ie:' + sDonateLink;
i18n.no.donate = 'Hvis du vil, kan du legge igjen en donasjon:' + sDonateLink;
i18n.el.donate = 'Î‘Î½ Î¸Î­Î»ÎµÏ„Îµ, Î¼Ï€Î¿ÏÎµÎ¯Ï„Îµ Î½Î± Î±Ï†Î®ÏƒÎµÏ„Îµ Î¼Î¹Î± Î´Ï‰ÏÎµÎ¬:' + sDonateLink;
i18n.ko.donate = 'ì¢‹ì•„í•˜ì‹œë©´ ê¸°ë¶€í•´ì£¼ì‹¤ ìˆ˜ ìˆìŠµë‹ˆë‹¤:' + sDonateLink;
i18n.vi.donate = 'Náº¿u báº¡n thÃ­ch, báº¡n cÃ³ thá»ƒ Ä‘á»ƒ láº¡i má»™t Ä‘Ã³ng gÃ³p:' + sDonateLink;
i18n.uk.donate = 'Ğ¯ĞºÑ‰Ğ¾ Ğ²Ğ°Ğ¼ Ğ¿Ğ¾Ğ´Ğ¾Ğ±Ğ°Ñ”Ñ‚ÑŒÑÑ Ñ†ĞµĞ¹ Ğ´Ğ¾Ğ´Ğ°Ñ‚Ğ¾Ğº, Ğ²Ğ¸ Ğ¼Ğ¾Ğ¶ĞµÑ‚Ğµ Ğ·Ğ°Ğ»Ğ¸ÑˆĞ¸Ñ‚Ğ¸ Ğ¿Ğ¾Ğ¶ĞµÑ€Ñ‚Ğ²Ñƒ:' + sDonateLink;
i18n.id.donate = 'Jika Anda menyukai aplikasi ini, Anda dapat memberikan donasi:' + sDonateLink;
i18n.ja.donate = 'ã‚ˆã‚ã—ã‘ã‚Œã°ã€å¯„ä»˜ã‚’ãŠé¡˜ã„ã—ã¾ã™: ' + sDonateLink;
i18n.hi.donate = 'à¤¯à¤¦à¤¿ à¤†à¤ª à¤šà¤¾à¤¹à¥‡à¤‚, à¤¤à¥‹ à¤†à¤ª à¤¦à¤¾à¤¨ à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚: ' + sDonateLink;
i18n.zh.donate = 'å¦‚æœæ‚¨æ„¿æ„ï¼Œæ‚¨å¯ä»¥ææ¬¾: ' + sDonateLink;
